version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: slidesync-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=slidesync
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slidesync-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/slidesync
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mongodb_data:

